create table t_time(
    id number generated by default as identity,
    nome varchar2(50),
    vitorias number default 0,
    empates number default 0,
    derrotas number default 0,
    gols_marcados number default 0,
    gols_sofridos number default 0,
    primary key(id)
);

create table t_partida(
    id number generated by default as identity,
    id_mandante number,
    id_visitante number,
    local varchar2(100),
    data date,
    gols_mandante number,
    gols_visitante number,
    primary key(id),
    foreign key(id_mandante) references t_time(id),
    foreign key(id_visitante) references t_time(id)
);