create table tb_enquete(
    id number generated by default as identity,
    nome varchar2(100),
    primary key(id)
);

create table tb_pergunta(
    id number generated by default as identity,
    numero number,
    questao varchar2(200),
    tipo varchar2(50),
    enquete_id number,
    primary key(id),
    foreign key(enquete_id) references tb_enquete(id)
);

create table tb_item(
    pergunta_id number,
    nome varchar2(50),
    foreign key(pergunta_id) references tb_pergunta(id)
);

create table tb_resposta(
    id number generated by default as identity,
    usuario varchar2(100),
    data date,
    resposta varchar2(500),
    pergunta_id number,
    foreign key(pergunta_id) references tb_pergunta(id)
);

insert into tb_enquete(nome) values('Esporte');
insert into tb_pergunta(numero, questao, tipo, enquete_id) values(1, 'Qual o time que você torce?','aberta', 1);

insert into tb_pergunta(numero, questao, tipo, enquete_id) values(2, 'Quem vai ganhar a Champions?','unica', 1);

insert into tb_pergunta(numero, questao, tipo, enquete_id) values(3, 'Quais são os melhores jogadores da Champions?', 'multipla', 1);

insert into tb_item(pergunta_id, nome) values(2, 'Barcelona');
insert into tb_item(pergunta_id, nome) values(2, 'Inter de Milão');
insert into tb_item(pergunta_id, nome) values(2, 'Arsenal');
insert into tb_item(pergunta_id, nome) values(2, 'PSG');

insert into tb_item(pergunta_id, nome) values(3, 'Raphinha');
insert into tb_item(pergunta_id, nome) values(3, 'Lewandovski');
insert into tb_item(pergunta_id, nome) values(3, 'Dembele');
insert into tb_item(pergunta_id, nome) values(3, 'Martinelli');
insert into tb_item(pergunta_id, nome) values(3, 'Lautaro');
insert into tb_item(pergunta_id, nome) values(3, 'Rodrygo');







